"aws_access_key_id": "AKIAYVP4CIPPLXEXA37R"
"access_id": "AKIAIOSFODNN7EXAMPLE"
"secret_access_key": "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"

# https://github.com/trufflesecurity/test_keys/blob/main/keys
